language: python
cache: pip
dist: xenial

python:
  - "3.6"
  - "3.7"

before_install:
  - pip install pip --upgrade

install:
  - pip install .[tests]

script:
  - pytest -rfsxEX --cov=openscm tests --cov-report term-missing
  - pip install .[notebooks]
  - pytest -rfsxEX --nbval ./notebooks --sanitize ./notebooks/tests_sanitize.cfg

after_success:
  - codecov
